import { useLang, type Lang } from "@/lib/lang";
import { copyZh } from "./copy-zh";

export const copy = {
  zh: copyZh,
  en: {
    nav: {
      work: "Work",
      gallery: "3D Gallery",
      drive: "Drive",
      foodtruck: "Food truck",
      studio: "Studio",
      contact: "Contact",
      open: "Open menu",
      close: "Close menu",
    },
    hero: {
      eyebrow: "Phitsanulok · Atelier",
      title: "SIRAWAT × BALL",
      lede: "A shared portfolio for AI, websites, music, and creative collaboration from Phitsanulok.",
      hint: "Drag to look · Click a frame",
      hintMobile: "Swipe to look · Tap a frame",
      enterGallery: "Enter 3D gallery",
      enterDrive: "Drive the grounds",
      viewWork: "View work",
    },
    manifesto: {
      index: "01",
      kicker: "Practice",
      title: "Two practices. One shared creative space.",
      body: "Sirawat works on AI, websites, and solar projects. Ball Anekprasong brings live folk music and open mic sessions. This portfolio explores how their work can meet through music, media, and the web.",
    },
    selected: {
      index: "02",
      kicker: "Selected",
      title: "Work that has to be walked through.",
      all: "All projects",
    },
    duo: {
      index: "03",
      kicker: "Principals",
      title: "Sirawat × Ball",
      sirawatRole: "AI & web projects",
      sirawatBody:
        "Sirawat (Ton) works on AI workflows, websites, and SIRINX solar projects. His portfolio brings these areas together with interactive presentation.",
      ballRole: "Live music & open mic",
      ballBody:
        "Ball Anekprasong hosts folk performances and open mic sessions, creating a space for people to sing and share music.",
      studioLink: "Read the studio",
    },
    process: {
      index: "04",
      kicker: "Method",
      title: "Listen, frame, build, place.",
      steps: [
        {
          n: "01",
          title: "Listen",
          body: "Site, culture, material, and the brief that was not written down.",
        },
        {
          n: "02",
          title: "Frame",
          body: "A verbal identity, a spatial concept, and the constraints that make them true.",
        },
        {
          n: "03",
          title: "Build",
          body: "Systems, models, motion, and prototypes — in two dimensions and in the round.",
        },
        {
          n: "04",
          title: "Place",
          body: "Install, launch, handoff. The work has to hold when we leave the room.",
        },
      ],
    },
    cta: {
      kicker: "Commissions",
      title: "Start a project.",
      body: "Discuss websites, creative media, live music, and possible collaborations from Phitsanulok.",
      button: "Write to the atelier",
    },
    work: {
      kicker: "Index",
      title: "All work",
      lede: "A collection of portfolio studies. Read each project’s evidence and status before treating it as completed client work.",
      filterAll: "All",
      empty: "No projects in this discipline yet.",
      view: "View project",
      open3d: "Open in 3D",
    },
    filters: {
      brand: "Brand",
      space: "Space",
      motion: "Motion",
      culture: "Culture",
    },
    case: {
      next: "Next",
      prev: "Previous",
      back: "All work",
      role: "Role",
      outcome: "Outcome",
      location: "Location",
      client: "Client",
      year: "Year",
      openGallery: "See it in 3D",
      inRoom: "This work in the room",
    },
    gallery: {
      kicker: "Room",
      title: "The atelier",
      hint: "Drag to look · Click a work · Arrows to cycle",
      hintMobile: "Drag to look · Tap a work",
      open: "Open case study",
      close: "Close",
      loading: "Preparing the room",
      inRoom: "In the room",
    },
    studio: {
      kicker: "Studio",
      title: "A room in Phitsanulok.",
      lede: "SIRAWAT × BALL is a shared portfolio for Sirawat (Ton) and Ball Anekprasong, bringing technology and music into one place.",
      p1: "Sirawat works on AI workflows, websites, and SIRINX solar projects. Ball brings folk music and open mic sessions. Their individual pages keep each person’s work distinct.",
      p2: "The shared portfolio is a proposed home for music, media, and web collaborations. The 3D gallery presents work and concepts; project status and supporting evidence determine what can be claimed as delivered.",
      materials: "Materials",
      bench: "The bench",
      sirawat: "Sirawat",
      ball: "Ball",
      sirawatRole: "AI & web projects",
      ballRole: "Folk musician & open mic host",
      sirawatBio:
        "Sirawat (Ton) works on AI, websites, and solar projects through SIRINX. This portfolio connects his technology work with creative presentation.",
      ballBio:
        "Ball Anekprasong performs folk music and hosts open mic sessions. His page focuses on music, performance, and participation.",
    },
    contact: {
      kicker: "Contact",
      title: "Prepare your brief.",
      lede: "Describe your project, save a copy on this device, then share it with the studio through your chosen channel.",
      name: "Name",
      email: "Email",
      type: "Project type",
      message: "Message",
      send: "Save brief on this device",
      sending: "Saving",
      sentTitle: "Saved on this device.",
      sentBody:
        "Your brief has not been sent. Download or copy it below, then share it with us. The desk on this browser holds your local copy.",
      another: "Prepare another brief",
      types: {
        brand: "Brand identity",
        space: "Spatial / interior",
        motion: "Motion / film",
        three: "3D / web",
        other: "Other",
      },
      addressLabel: "Studio",
      address: "Phitsanulok, Thailand",
      note: "Enquiries are stored on this device so you can leave and return. Nothing is sent to a server.",
      errName: "Please add your name (2–120 characters).",
      errEmail: "Please add a valid email.",
      errMessage: "Please write a short brief (8–10,000 characters).",
      channel: "Reply channel",
      handle: "LINE ID / email / phone",
      channels: { line: "LINE", email: "Email", phone: "Phone" },
      errHandle: "Please enter a valid contact for the chosen channel.",
      download: "Download brief",
      copyBrief: "Copy brief",
      copied: "Brief copied. Share it through your preferred channel.",
      copyError: "Copy was unavailable. Download your brief instead.",
      handoff: "Open Sirawat’s Facebook",
      handoffNote:
        "This opens the owner’s confirmed profile. Send the brief yourself; opening the link does not deliver it.",
      deskHint: "Open local desk",
    },
    footer: {
      wordmark: "SIRAWAT × BALL",
      line: "Creative atelier · Phitsanulok",
      work: "Work",
      gallery: "3D Gallery",
      drive: "Drive",
      foodtruck: "Food truck",
      studio: "Studio",
      contact: "Contact",
    },
    notFound: {
      title: "This room is empty.",
      body: "That project is not in the index.",
      back: "Back to work",
    },
    fallback: {
      webgl: "The 3D room could not open on this device. The work is still in the index.",
    },
    drive: {
      loading: "Preparing the grounds",
    },
    ops: {
      kicker: "Local operations",
      localTitle: "Local workspace",
      localNotice:
        "Private to this browser profile. Data is not shared with the studio or other devices. Anyone using this profile can read it. Reminders update while this page is open; no messages are sent.",
      loading: "Loading local data…",
      storageError:
        "Local storage could not be read or saved. Your change was not saved. Allow browser storage or export your brief manually; existing data has not been replaced.",
      retry: "Retry storage",
      exportData: "Download local backup",
      importData: "Restore backup",
      importError: "This backup is invalid or exceeds 5 MB. Nothing was replaced.",
      restoreNonempty:
        "Restore requires an empty workspace. Use another browser profile to inspect this backup without replacing local work.",
      imported: "Backup restored on this device.",
      backupNotice:
        "Backups include names, contact details, messages, and drafts. Keep them private. Restore works in an empty workspace and never overwrites existing work.",
      actionError: "This action could not be saved. Refresh the local data and try again.",
      downloadDraft: "Download this draft",

      desk: "Desk",
      marketing: "Marketing",
      automations: "Automations",
      kit: "Kit",
      deskTitle: "The desk.",
      deskLede:
        "Saved briefs become local tasks and reminders. Assign an owner, mark a quote as prepared, and close the record. These actions do not contact the studio or create a quote document.",
      emptyDesk: "No enquiries in this view. The contact form writes here.",
      assign: "Assign",
      quote: "Mark quote prepared",
      close: "Close",
      assignee: "Assignee",
      filters: {
        open: "Open",
        received: "Saved locally",
        assigned: "Assigned",
        quoted: "Quote prepared",
        closed: "Closed",
      },
      status: {
        received: "Saved locally",
        assigned: "Assigned",
        quoted: "Quote prepared",
        closed: "Closed",
      },
      jobs: {
        staff_task: "Staff task",
        sla_watch: "SLA watch",
        quote_followup: "Quote follow-up",
      },
      jobStatus: {
        queued: "Queued",
        running: "Running",
        done: "Done",
        overdue: "Overdue",
        dead_letter: "Parked",
      },
      marketingTitle: "Channel drafts.",
      marketingLede:
        "Draft English, Thai, and Chinese copy for LINE, Facebook, Instagram, TikTok, Google, and the site. Ready checks titles and minimum body length in all three languages; it does not fact-check, send, or publish anything.",
      editDraft: "Edit draft",
      editDraftTitle: "Edit draft title",
      needsTranslation:
        "This older draft has no Chinese translation. Add a Chinese title and body before marking all three languages ready.",
      markReady: "Mark ready",
      noSend: "Send is off",
      blockedBody:
        "Write a title and at least 20 characters of body text in English, Thai, and Chinese before marking this draft ready.",
      draftStatus: {
        draft: "Draft",
        ready: "Ready",
        blocked: "Blocked",
      },
      channels: {
        line: "LINE OA",
        facebook: "Facebook",
        instagram: "Instagram",
        tiktok: "TikTok",
        google: "Google Business",
        web: "Website",
      },
      autoTitle: "Automations.",
      autoLede:
        "Local reminders are evaluated when this page opens and every 15 seconds while it stays open. Overdue items remain visible when you return. There is no background worker or external delivery.",
      runTick: "Run SLA tick",
      emptyJobs: "No jobs yet. Save a brief locally to create the first two.",
      due: "Due",
      park: "Park",
      statOpen: "Open",
      statQueue: "In flight",
      statOverdue: "Overdue",
      statReady: "Ready drafts",
      kitTitle: "Reusable kit.",
      kitLede:
        "Same core: 3D salon, grounds, enquiry, desk, drafts, jobs. Swap photography, copy, and channel facts for the next house, villa, or service — do not copy live rates or another brand’s rooms.",
      reuse: [
        {
          title: "Guest site",
          body: "Home, gallery, drive, work, contact. Inquiry-first. No fake calendar, no OTA.",
        },
        {
          title: "Operations",
          body: "Desk, marketing drafts, SLA jobs. State stays on the device until a real connector is approved.",
        },
        {
          title: "Models",
          body: "Blender MCP in two passes: structure from a plan, then polish. Geometry fallback until a GLB exists.",
        },
      ],
      channelsTitle: "Channel roles",
      channelsLede:
        "A proposed channel plan: adapt each role to your audience. These connectors are not active in this workspace.",
      channelFacts: [
        {
          channel: "LINE OA",
          body: "Plan direct conversations and first-reply drafts. Broadcast is not enabled.",
        },
        {
          channel: "Google",
          body: "Maps and Business Profile are how people find a studio. Facts only. No invented rating.",
        },
        {
          channel: "Instagram / TikTok",
          body: "Discovery. The salon and the grounds are the footage. Measure inquiries, not likes.",
        },
        {
          channel: "Facebook",
          body: "Community and longer notes. Not a live-selling floor for this atelier.",
        },
      ],
      liveTitle: "Working here",
      liveItems: [
        "3D salon and drive grounds",
        "Enquiry → staff task + SLA",
        "Desk assign / quote / close",
        "Marketing drafts with a ready gate",
        "EN / TH / 中文 together",
      ],
      blockedTitle: "Not on this host",
      blockedItems: [
        "LINE / Meta / Google send",
        "Moshi-hook pairing (Mac / Homebrew, not this preview)",
        "Blender GUI / Astra quota routing",
        "Payments, PMS, confirmed reservations",
      ],
      studioOps: "Operations",
      deskCard: "Desk — enquiries and quotes",
      marketingCard: "Marketing — six channel drafts",
      autoCard: "Automations — SLA jobs",
      kitCard: "Kit — how to reuse the core",
    },
  },
  th: {
    nav: {
      work: "งาน",
      gallery: "แกลเลอรี 3D",
      drive: "ขับ",
      foodtruck: "ฟู้ดทรัก",
      studio: "สตูดิโอ",
      contact: "ติดต่อ",
      open: "เปิดเมนู",
      close: "ปิดเมนู",
    },
    hero: {
      eyebrow: "พิษณุโลก · ห้องทำงาน",
      title: "SIRAWAT × BALL",
      lede: "พอร์ตโฟลิโอร่วมด้าน AI เว็บไซต์ ดนตรี และงานสร้างสรรค์จากพิษณุโลก",
      hint: "ลากเพื่อมอง · คลิกกรอบภาพ",
      hintMobile: "ปัดเพื่อมอง · แตะกรอบภาพ",
      enterGallery: "เข้าแกลเลอรี 3D",
      enterDrive: "ขับในลาน",
      viewWork: "ดูงาน",
    },
    manifesto: {
      index: "01",
      kicker: "แนวทาง",
      title: "สองแนวทาง หนึ่งพื้นที่สร้างสรรค์ร่วมกัน",
      body: "ศิรวัฒน์ทำงานด้าน AI เว็บไซต์ และโครงการโซลาร์ พี่บอลอเนกประสงค์นำดนตรีโฟลคและกิจกรรมเปิดไมค์มาร่วม พอร์ตนี้นำเสนอแนวทางที่เทคโนโลยี ดนตรี และสื่อจะทำงานร่วมกัน",
    },
    selected: {
      index: "02",
      kicker: "คัดสรร",
      title: "งานที่ต้องเดินเข้าไปดู",
      all: "งานทั้งหมด",
    },
    duo: {
      index: "03",
      kicker: "ผู้ก่อตั้ง",
      title: "ศิรวัฒน์ × บอล",
      sirawatRole: "AI และเว็บไซต์",
      sirawatBody:
        "ศิรวัฒน์ (ต้น) ทำงานด้านระบบ AI เว็บไซต์ และโครงการโซลาร์ SIRINX พอร์ตนี้นำงานเหล่านี้มาเสนอในรูปแบบอินเทอร์แอคทีฟ",
      ballRole: "ดนตรีสดและเปิดไมค์",
      ballBody:
        "พี่บอลอเนกประสงค์ทำกิจกรรมดนตรีโฟลคและเปิดไมค์ สร้างพื้นที่ให้ผู้คนร้องเพลงและแบ่งปันดนตรีร่วมกัน",
      studioLink: "อ่านเรื่องสตูดิโอ",
    },
    process: {
      index: "04",
      kicker: "วิธีทำงาน",
      title: "ฟัง วางกรอบ สร้าง วางลงที่",
      steps: [
        {
          n: "01",
          title: "ฟัง",
          body: "พื้นที่ วัฒนธรรม วัสดุ และโจทย์ที่ยังไม่ได้เขียน",
        },
        {
          n: "02",
          title: "วางกรอบ",
          body: "อัตลักษณ์ทางภาษา แนวคิดของพื้นที่ และข้อจำกัดที่ทำให้มันจริง",
        },
        {
          n: "03",
          title: "สร้าง",
          body: "ระบบ โมเดล โมชัน และต้นแบบ — ทั้งระนาบและรอบตัว",
        },
        {
          n: "04",
          title: "วางลงที่",
          body: "ติดตั้ง เปิดตัว ส่งมอบ งานต้องอยู่ได้เมื่อเราออกจากห้อง",
        },
      ],
    },
    cta: {
      kicker: "งานจ้าง",
      title: "เริ่มโปรเจกต์",
      body: "คุยเรื่องเว็บไซต์ สื่อสร้างสรรค์ ดนตรีสด และแนวทางทำงานร่วมกันจากพิษณุโลก",
      button: "เขียนถึงห้องทำงาน",
    },
    work: {
      kicker: "สารบัญ",
      title: "งานทั้งหมด",
      lede: "รวมผลงานและงานศึกษาในพอร์ต อ่านสถานะและหลักฐานของแต่ละโครงการก่อนอ้างว่าเป็นงานลูกค้าที่ส่งมอบแล้ว",
      filterAll: "ทั้งหมด",
      empty: "ยังไม่มีงานในสาขานี้",
      view: "ดูโปรเจกต์",
      open3d: "เปิดในสามมิติ",
    },
    filters: {
      brand: "แบรนด์",
      space: "พื้นที่",
      motion: "โมชัน",
      culture: "วัฒนธรรม",
    },
    case: {
      next: "ถัดไป",
      prev: "ก่อนหน้า",
      back: "งานทั้งหมด",
      role: "บทบาท",
      outcome: "ผลลัพธ์",
      location: "สถานที่",
      client: "ลูกค้า",
      year: "ปี",
      openGallery: "ดูในสามมิติ",
      inRoom: "งานนี้ในห้อง",
    },
    gallery: {
      kicker: "ห้อง",
      title: "ห้องทำงาน",
      hint: "ลากเพื่อมอง · คลิกงาน · ลูกศรเพื่อเลื่อน",
      hintMobile: "ลากเพื่อมอง · แตะงาน",
      open: "เปิดเคส",
      close: "ปิด",
      loading: "กำลังจัดห้อง",
      inRoom: "ในห้อง",
    },
    studio: {
      kicker: "สตูดิโอ",
      title: "ห้องหนึ่งในพิษณุโลก",
      lede: "SIRAWAT × BALL คือพอร์ตโฟลิโอร่วมของศิรวัฒน์ (ต้น) และพี่บอลอเนกประสงค์ ที่นำเทคโนโลยีและดนตรีมาอยู่ในพื้นที่เดียวกัน",
      p1: "ศิรวัฒน์ทำงานด้านระบบ AI เว็บไซต์ และโครงการโซลาร์ SIRINX พี่บอลนำดนตรีโฟลคและกิจกรรมเปิดไมค์มาร่วม หน้าส่วนบุคคลแยกผลงานของแต่ละคนให้ชัดเจน",
      p2: "พอร์ตร่วมเป็นพื้นที่ที่เสนอไว้สำหรับงานดนตรี สื่อ และเว็บไซต์ แกลเลอรี 3D นำเสนอทั้งงานและแนวคิด โดยอ้างอิงสถานะและหลักฐานของแต่ละโครงการเมื่อต้องกล่าวถึงงานที่ส่งมอบแล้ว",
      materials: "วัสดุ",
      bench: "โต๊ะงาน",
      sirawat: "ศิรวัฒน์",
      ball: "บอล",
      sirawatRole: "AI และเว็บไซต์",
      ballRole: "นักดนตรีโฟลคและผู้จัดกิจกรรมเปิดไมค์",
      sirawatBio:
        "ศิรวัฒน์ (ต้น) ทำงานด้าน AI เว็บไซต์ และโครงการโซลาร์ผ่าน SIRINX พอร์ตนี้เชื่อมงานเทคโนโลยีกับการนำเสนอเชิงสร้างสรรค์",
      ballBio:
        "พี่บอลอเนกประสงค์เล่นดนตรีโฟลคและทำกิจกรรมเปิดไมค์ หน้าของพี่บอลเน้นดนตรี การแสดง และการมีส่วนร่วมของผู้ชม",
    },
    contact: {
      kicker: "ติดต่อ",
      title: "เตรียมบรีฟของคุณ",
      lede: "เล่าโครงการ บันทึกสำเนาบนอุปกรณ์นี้ แล้วส่งต่อให้สตูดิโอผ่านช่องทางที่คุณเลือก",
      name: "ชื่อ",
      email: "อีเมล",
      type: "ประเภทงาน",
      message: "ข้อความ",
      send: "บันทึกบรีฟบนอุปกรณ์นี้",
      sending: "กำลังบันทึก",
      sentTitle: "บันทึกบนอุปกรณ์นี้แล้ว",
      sentBody:
        "บรีฟยังไม่ได้ส่ง ดาวน์โหลดหรือคัดลอกด้านล่าง แล้วส่งต่อให้เรา โต๊ะงานในเบราว์เซอร์นี้เก็บสำเนาไว้ให้คุณ",
      another: "เตรียมบรีฟอีกฉบับ",
      types: {
        brand: "อัตลักษณ์แบรนด์",
        space: "พื้นที่ / ภายใน",
        motion: "โมชัน / ภาพยนตร์",
        three: "สามมิติ / เว็บ",
        other: "อื่น ๆ",
      },
      addressLabel: "สตูดิโอ",
      address: "พิษณุโลก ประเทศไทย",
      note: "ข้อความถูกเก็บบนอุปกรณ์นี้ เพื่อให้คุณออกแล้วกลับมาได้ ไม่ได้ส่งขึ้นเซิร์ฟเวอร์",
      errName: "กรุณาใส่ชื่อ 2–120 ตัวอักษร",
      errEmail: "กรุณาใส่อีเมลที่ถูกต้อง",
      errMessage: "กรุณาเขียนสรุปงาน 8–10,000 ตัวอักษร",
      channel: "ช่องทางตอบกลับ",
      handle: "LINE ID / อีเมล / โทรศัพท์",
      channels: { line: "LINE", email: "อีเมล", phone: "โทรศัพท์" },
      errHandle: "กรุณาใส่ข้อมูลติดต่อให้ตรงกับช่องทางที่เลือก",
      download: "ดาวน์โหลดบรีฟ",
      copyBrief: "คัดลอกบรีฟ",
      copied: "คัดลอกแล้ว ส่งต่อผ่านช่องทางที่คุณเลือกได้เลย",
      copyError: "คัดลอกไม่ได้ กรุณาดาวน์โหลดบรีฟแทน",
      handoff: "เปิด Facebook ของศิรวัฒน์",
      handoffNote:
        "ลิงก์เปิดโปรไฟล์ที่เจ้าของยืนยัน กรุณาส่งบรีฟด้วยตัวเอง การเปิดลิงก์ยังไม่ใช่การส่งข้อความ",
      deskHint: "เปิดโต๊ะงานในเครื่อง",
    },
    footer: {
      wordmark: "SIRAWAT × BALL",
      line: "สตูดิโอสร้างสรรค์ · พิษณุโลก",
      work: "งาน",
      gallery: "แกลเลอรี 3D",
      drive: "ขับ",
      foodtruck: "ฟู้ดทรัก",
      studio: "สตูดิโอ",
      contact: "ติดต่อ",
    },
    notFound: {
      title: "ห้องนี้ว่าง",
      body: "โปรเจกต์นั้นไม่อยู่ในสารบัญ",
      back: "กลับไปที่งาน",
    },
    fallback: {
      webgl: "เปิดห้องสามมิติบนอุปกรณ์นี้ไม่ได้ งานยังอยู่ในสารบัญ",
    },
    drive: {
      loading: "กำลังจัดลาน",
    },
    ops: {
      kicker: "ปฏิบัติการในเครื่อง",
      localTitle: "พื้นที่งานในเครื่อง",
      localNotice:
        "ข้อมูลอยู่ในโปรไฟล์เบราว์เซอร์นี้ ไม่ได้แชร์ให้สตูดิโอหรืออุปกรณ์อื่น ผู้ใช้โปรไฟล์นี้อ่านข้อมูลได้ การเตือนอัปเดตเมื่อเปิดหน้านี้เท่านั้น ไม่มีการส่งข้อความ",
      loading: "กำลังอ่านข้อมูลในเครื่อง…",
      storageError:
        "อ่านหรือบันทึกข้อมูลในเบราว์เซอร์ไม่ได้ การเปลี่ยนแปลงยังไม่ถูกบันทึก กรุณาอนุญาตพื้นที่จัดเก็บหรือดาวน์โหลดบรีฟเอง ข้อมูลเดิมยังไม่ถูกเขียนทับ",
      retry: "ลองอ่านข้อมูลอีกครั้ง",
      exportData: "ดาวน์โหลดข้อมูลสำรอง",
      importData: "กู้คืนข้อมูลสำรอง",
      importError: "ไฟล์สำรองไม่ถูกต้องหรือใหญ่กว่า 5 MB ไม่มีการเขียนทับข้อมูล",
      restoreNonempty:
        "ต้องกู้คืนในพื้นที่งานว่าง ใช้โปรไฟล์เบราว์เซอร์อื่นเพื่อตรวจไฟล์นี้โดยไม่เขียนทับงานเดิม",
      imported: "กู้คืนข้อมูลบนอุปกรณ์นี้แล้ว",
      backupNotice:
        "ไฟล์สำรองมีชื่อ ช่องทางติดต่อ ข้อความ และฉบับร่าง ควรเก็บเป็นส่วนตัว กู้คืนได้ในพื้นที่งานว่างและไม่เขียนทับงานเดิม",
      actionError: "บันทึกการทำงานนี้ไม่ได้ กรุณาโหลดข้อมูลในเครื่องแล้วลองอีกครั้ง",
      downloadDraft: "ดาวน์โหลดฉบับร่างนี้",

      desk: "โต๊ะงาน",
      marketing: "การตลาด",
      automations: "อัตโนมัติ",
      kit: "โครง",
      deskTitle: "โต๊ะงาน",
      deskLede:
        "บรีฟที่บันทึกสร้างงานและการเตือนในเครื่อง มอบหมาย ระบุว่าเตรียมใบเสนอแล้ว และปิดรายการ การกดไม่ติดต่อสตูดิโอหรือสร้างเอกสารใบเสนอ",
      emptyDesk: "ยังไม่มีข้อความในมุมนี้ ฟอร์มติดต่อเขียนเข้าที่นี่",
      assign: "มอบหมาย",
      quote: "ระบุว่าเตรียมใบเสนอแล้ว",
      close: "ปิด",
      assignee: "ผู้รับ",
      filters: {
        open: "เปิด",
        received: "บันทึกในเครื่อง",
        assigned: "มอบหมายแล้ว",
        quoted: "ร่างแล้ว",
        closed: "ปิดแล้ว",
      },
      status: {
        received: "บันทึกในเครื่อง",
        assigned: "มอบหมายแล้ว",
        quoted: "ร่างแล้ว",
        closed: "ปิดแล้ว",
      },
      jobs: {
        staff_task: "งานพนักงาน",
        sla_watch: "เฝ้า SLA",
        quote_followup: "ติดตามใบเสนอ",
      },
      jobStatus: {
        queued: "คิว",
        running: "กำลังทำ",
        done: "เสร็จ",
        overdue: "เกินกำหนด",
        dead_letter: "พักไว้",
      },
      marketingTitle: "ฉบับร่างช่องทาง",
      marketingLede:
        "ร่างข้อความอังกฤษ ไทย และจีนสำหรับ LINE เฟซบุ๊ก อินสตาแกรม ติ๊กต็อก กูเกิล และเว็บ สถานะพร้อมตรวจชื่อและความยาวเนื้อหาขั้นต่ำครบสามภาษา ไม่ได้ตรวจข้อเท็จจริง ส่ง หรือเผยแพร่ข้อความ",
      editDraft: "แก้ฉบับร่าง",
      editDraftTitle: "แก้ชื่อฉบับร่าง",
      needsTranslation:
        "ฉบับร่างเดิมยังไม่มีคำแปลจีน เพิ่มชื่อและเนื้อหาภาษาจีนก่อนตั้งทั้งสามภาษาเป็นพร้อม",
      markReady: "ตั้งเป็นพร้อม",
      noSend: "ส่งยังปิด",
      blockedBody:
        "ใส่ชื่อและเนื้อหาอย่างน้อย 20 ตัวอักษรในภาษาอังกฤษ ไทย และจีน ก่อนตั้งฉบับร่างเป็นพร้อม",
      draftStatus: {
        draft: "ร่าง",
        ready: "พร้อม",
        blocked: "ถูกบล็อก",
      },
      channels: {
        line: "LINE OA",
        facebook: "เฟซบุ๊ก",
        instagram: "อินสตาแกรม",
        tiktok: "ติ๊กต็อก",
        google: "Google Business",
        web: "เว็บไซต์",
      },
      autoTitle: "งานอัตโนมัติ",
      autoLede:
        "ตรวจการเตือนในเครื่องเมื่อเปิดหน้านี้และทุก 15 วินาทีขณะเปิดหน้า รายการเกินกำหนดจะแสดงเมื่อกลับมา ไม่มีตัวทำงานเบื้องหลังหรือการส่งออกภายนอก",
      runTick: "เดินนาฬิกา SLA",
      emptyJobs: "ยังไม่มีงาน บันทึกบรีฟในเครื่องเพื่อสร้างสองงานแรก",
      due: "ครบกำหนด",
      park: "พักไว้",
      statOpen: "เปิด",
      statQueue: "กำลังทำ",
      statOverdue: "เกินกำหนด",
      statReady: "ร่างพร้อม",
      kitTitle: "โครงที่ใช้ซ้ำ",
      kitLede:
        "แกนเดียวกัน: แกลเลอรี 3D ลาน ข้อความ โต๊ะงาน ฉบับร่าง งาน SLA เปลี่ยนภาพ คำ และข้อเท็จจริงช่องทางให้บ้านหลังถัดไป วิลล่า หรือบริการ — อย่าคัดลอกเรทสดหรือห้องของแบรนด์อื่น",
      reuse: [
        {
          title: "เว็บผู้มาเยือน",
          body: "หน้าแรก แกลเลอรี ลาน งาน ติดต่อ สอบถามก่อน ไม่มีปฏิทินปลอม ไม่มี OTA",
        },
        {
          title: "ปฏิบัติการ",
          body: "โต๊ะงาน ฉบับร่างการตลาด งาน SLA สถานะอยู่บนอุปกรณ์จนกว่าจะอนุมัติตัวเชื่อมจริง",
        },
        {
          title: "โมเดล",
          body: "Blender MCP สองรอบ: โครงสร้างจากแปลน แล้วจึงตกแต่ง มีเรขาคณิตสำรองจนกว่าจะมี GLB",
        },
      ],
      channelsTitle: "บทบาทของช่องทาง",
      channelsLede:
        "แผนช่องทางที่เสนอ ปรับบทบาทให้เหมาะกับผู้ชม ตัวเชื่อมเหล่านี้ยังไม่ได้เปิดใช้ในพื้นที่งานนี้",
      channelFacts: [
        {
          channel: "LINE OA",
          body: "วางแผนบทสนทนาตรงและฉบับร่างคำตอบแรก ยังไม่เปิดบรอดแคสต์",
        },
        {
          channel: "Google",
          body: "แผนที่และ Business Profile คือทางหาสตูดิโอ เฉพาะข้อเท็จจริง ไม่แต่งเรตติ้ง",
        },
        {
          channel: "Instagram / TikTok",
          body: "การค้นพบ ห้องและลานคือภาพ วัดจากข้อความ ไม่ใช่ไลก์",
        },
        {
          channel: "Facebook",
          body: "ชุมชนและบันทึกยาว ไม่ใช่พื้นขายไลฟ์ของห้องทำงานนี้",
        },
      ],
      liveTitle: "ทำงานแล้วที่นี่",
      liveItems: [
        "แกลเลอรี 3D และลานขับ",
        "ข้อความ → งานพนักงาน + SLA",
        "โต๊ะงาน มอบหมาย / ร่างใบเสนอ / ปิด",
        "ฉบับร่างการตลาดพร้อมเกณฑ์ความยาว",
        "EN / TH / 中文 พร้อมกัน",
      ],
      blockedTitle: "ไม่บนโฮสต์นี้",
      blockedItems: [
        "การส่ง LINE / Meta / Google",
        "จับคู่ Moshi-hook (แม็ก / Homebrew ไม่ใช่พรีวิวนี้)",
        "Blender GUI / การจัดโควตา Astra",
        "การชำระเงิน PMS การจองที่ยืนยัน",
      ],
      studioOps: "ปฏิบัติการ",
      deskCard: "โต๊ะงาน — ข้อความและใบเสนอ",
      marketingCard: "การตลาด — หกฉบับร่าง",
      autoCard: "อัตโนมัติ — งาน SLA",
      kitCard: "โครง — วิธีใช้แกนซ้ำ",
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function useCopy(): Copy {
  const lang = useLang((s) => s.lang);
  return copy[lang];
}

export function useLocale(): Lang {
  return useLang((s) => s.lang);
}
