import { useLang, type Lang } from "@/lib/lang";

export const copy = {
  en: {
    nav: {
      work: "Work",
      gallery: "3D Gallery",
      drive: "Drive",
      studio: "Studio",
      contact: "Contact",
      open: "Open menu",
      close: "Close menu",
    },
    hero: {
      eyebrow: "Phitsanulok · Atelier",
      title: "SIRAWAT × BALL",
      lede: "A two-principal studio for brand worlds, spatial identity, and cinematic digital work.",
      hint: "Drag to look · Click a frame",
      hintMobile: "Swipe to look · Tap a frame",
      enterGallery: "Enter 3D gallery",
      enterDrive: "Drive the grounds",
      viewWork: "View work",
    },
    manifesto: {
      index: "01",
      kicker: "Practice",
      title: "Two principals. One room. We design the identity of places — and the places of identity.",
      body: "Sirawat builds the verbal and visual system. Ball builds the space it lives in — rooms, objects, and real-time 3D. Together we treat a brand as somewhere you can stand.",
    },
    selected: {
      index: "02",
      kicker: "Selected",
      title: "Work that has to be walked through.",
      all: "All projects",
    },
    duo: {
      index: "03",
      kicker: "Principals",
      title: "Sirawat × Ball",
      sirawatRole: "Creative direction",
      sirawatBody:
        "Brand systems, type, and narrative. Sirawat frames the story so a place knows how to speak — before a single wall is drawn.",
      ballRole: "Spatial design",
      ballBody:
        "Rooms, objects, and interactive 3D. Ball translates the system into space you can orbit, enter, and remember.",
      studioLink: "Read the studio",
    },
    process: {
      index: "04",
      kicker: "Method",
      title: "Listen, frame, build, place.",
      steps: [
        {
          n: "01",
          title: "Listen",
          body: "Site, culture, material, and the brief that was not written down.",
        },
        {
          n: "02",
          title: "Frame",
          body: "A verbal identity, a spatial concept, and the constraints that make them true.",
        },
        {
          n: "03",
          title: "Build",
          body: "Systems, models, motion, and prototypes — in two dimensions and in the round.",
        },
        {
          n: "04",
          title: "Place",
          body: "Install, launch, handoff. The work has to hold when we leave the room.",
        },
      ],
    },
    cta: {
      kicker: "Commissions",
      title: "Start a project.",
      body: "Identity, interiors, exhibitions, and real-time 3D — from Phitsanulok, for rooms anywhere.",
      button: "Write to the atelier",
    },
    work: {
      kicker: "Index",
      title: "All work",
      lede: "Brand, space, motion, culture — eight rooms from the last few years.",
      filterAll: "All",
      empty: "No projects in this discipline yet.",
      view: "View project",
      open3d: "Open in 3D",
    },
    filters: {
      brand: "Brand",
      space: "Space",
      motion: "Motion",
      culture: "Culture",
    },
    case: {
      next: "Next",
      prev: "Previous",
      back: "All work",
      role: "Role",
      outcome: "Outcome",
      location: "Location",
      client: "Client",
      year: "Year",
      openGallery: "See it in 3D",
      inRoom: "This work in the room",
    },
    gallery: {
      kicker: "Room",
      title: "The atelier",
      hint: "Drag to look · Click a work · Arrows to cycle",
      hintMobile: "Drag to look · Tap a work",
      open: "Open case study",
      close: "Close",
      loading: "Preparing the room",
      inRoom: "In the room",
    },
    studio: {
      kicker: "Studio",
      title: "A room in Phitsanulok.",
      lede: "SIRAWAT × BALL is a two-person atelier. We work in brand, space, and motion — usually on the same project, always in the same conversation.",
      p1: "The practice started as a shared desk and a disagreement about type. It is now a method: Sirawat writes the system; Ball builds the place it occupies. Clients come for identity and leave with a room, a film, or a 3D world that can be walked.",
      p2: "We take a small number of commissions each year — hospitality, culture, and independent product. The 3D gallery on this site is not a metaphor. It is how we present work: as objects in space, not a grid that forgot it had weight.",
      materials: "Materials",
      bench: "The bench",
      sirawat: "Sirawat",
      ball: "Ball",
      sirawatRole: "Creative director",
      ballRole: "Spatial designer",
      sirawatBio:
        "Leads identity, editorial, and verbal systems. Trained in graphic design; thinks in sequences, paper, and the sentence a room should say out loud.",
      ballBio:
        "Leads space, object, and real-time 3D. Trained in interior and digital form; thinks in light, mass, and how a camera should enter.",
    },
    contact: {
      kicker: "Contact",
      title: "Write to us.",
      lede: "Tell us the room, the brand, or the film. We reply from Phitsanulok, usually within a few days.",
      name: "Name",
      email: "Email",
      type: "Project type",
      message: "Message",
      send: "Send enquiry",
      sending: "Sending",
      sentTitle: "Received.",
      sentBody: "Thank you. We will write back from the atelier.",
      another: "Send another",
      types: {
        brand: "Brand identity",
        space: "Spatial / interior",
        motion: "Motion / film",
        three: "3D / web",
        other: "Other",
      },
      addressLabel: "Studio",
      address: "Phitsanulok, Thailand",
      mailLabel: "Email",
      mail: "hello@sirawatball.studio",
      note: "Enquiries are stored on this device so you can leave and return. Nothing is sent to a server.",
      errName: "Please add your name.",
      errEmail: "Please add a valid email.",
      errMessage: "Please write a short brief.",
    },
    footer: {
      wordmark: "SIRAWAT × BALL",
      line: "Creative atelier · Phitsanulok",
      work: "Work",
      gallery: "3D Gallery",
      drive: "Drive",
      studio: "Studio",
      contact: "Contact",
    },
    notFound: {
      title: "This room is empty.",
      body: "That project is not in the index.",
      back: "Back to work",
    },
    fallback: {
      webgl: "The 3D room could not open on this device. The work is still in the index.",
    },
    drive: {
      loading: "Preparing the grounds",
    },
  },
  th: {
    nav: {
      work: "งาน",
      gallery: "แกลเลอรี 3D",
      drive: "ขับ",
      studio: "สตูดิโอ",
      contact: "ติดต่อ",
      open: "เปิดเมนู",
      close: "ปิดเมนู",
      },
    hero: {
      eyebrow: "พิษณุโลก · ห้องทำงาน",
      title: "SIRAWAT × BALL",
      lede: "สตูดิโอสองคน สำหรับโลกแบรนด์ อัตลักษณ์ของพื้นที่ และงานดิจิทัลแบบภาพยนตร์",
      hint: "ลากเพื่อมอง · คลิกกรอบภาพ",
      hintMobile: "ปัดเพื่อมอง · แตะกรอบภาพ",
      enterGallery: "เข้าแกลเลอรี 3D",
      enterDrive: "ขับในลาน",
      viewWork: "ดูงาน",
    },
    manifesto: {
      index: "01",
      kicker: "แนวทาง",
      title: "สองคน หนึ่งห้อง เราออกแบบอัตลักษณ์ของสถานที่ — และสถานที่ให้อัตลักษณ์",
      body: "ศิรวัฒน์สร้างระบบคำและภาพ บอลสร้างพื้นที่ที่ระบบนั้นอาศัย — ห้อง วัตถุ และสามมิติแบบเรียลไทม์ เรามองแบรนด์เป็นที่ที่ยืนได้",
    },
    selected: {
      index: "02",
      kicker: "คัดสรร",
      title: "งานที่ต้องเดินเข้าไปดู",
      all: "งานทั้งหมด",
    },
    duo: {
      index: "03",
      kicker: "ผู้ก่อตั้ง",
      title: "ศิรวัฒน์ × บอล",
      sirawatRole: "กำกับศิลป์",
      sirawatBody:
        "ระบบแบรนด์ ตัวพิมพ์ และเรื่องเล่า ศิรวัฒน์วางกรอบเรื่องก่อนที่จะมีผนังสักด้าน",
      ballRole: "ออกแบบพื้นที่",
      ballBody:
        "ห้อง วัตถุ และสามมิติแบบอินเทอร์แอคทีฟ บอลแปลระบบให้เป็นพื้นที่ที่โคจร เข้าถึง และจดจำได้",
      studioLink: "อ่านเรื่องสตูดิโอ",
    },
    process: {
      index: "04",
      kicker: "วิธีทำงาน",
      title: "ฟัง วางกรอบ สร้าง วางลงที่",
      steps: [
        {
          n: "01",
          title: "ฟัง",
          body: "พื้นที่ วัฒนธรรม วัสดุ และโจทย์ที่ยังไม่ได้เขียน",
        },
        {
          n: "02",
          title: "วางกรอบ",
          body: "อัตลักษณ์ทางภาษา แนวคิดของพื้นที่ และข้อจำกัดที่ทำให้มันจริง",
        },
        {
          n: "03",
          title: "สร้าง",
          body: "ระบบ โมเดล โมชัน และต้นแบบ — ทั้งระนาบและรอบตัว",
        },
        {
          n: "04",
          title: "วางลงที่",
          body: "ติดตั้ง เปิดตัว ส่งมอบ งานต้องอยู่ได้เมื่อเราออกจากห้อง",
        },
      ],
    },
    cta: {
      kicker: "งานจ้าง",
      title: "เริ่มโปรเจกต์",
      body: "อัตลักษณ์ ภายในนิทรรศการ และสามมิติแบบเรียลไทม์ — จากพิษณุโลก สำหรับห้องที่ไหนก็ได้",
      button: "เขียนถึงห้องทำงาน",
    },
    work: {
      kicker: "สารบัญ",
      title: "งานทั้งหมด",
      lede: "แบรนด์ พื้นที่ โมชัน วัฒนธรรม — แปดห้องในช่วงหลายปีที่ผ่านมา",
      filterAll: "ทั้งหมด",
      empty: "ยังไม่มีงานในสาขานี้",
      view: "ดูโปรเจกต์",
      open3d: "เปิดในสามมิติ",
    },
    filters: {
      brand: "แบรนด์",
      space: "พื้นที่",
      motion: "โมชัน",
      culture: "วัฒนธรรม",
    },
    case: {
      next: "ถัดไป",
      prev: "ก่อนหน้า",
      back: "งานทั้งหมด",
      role: "บทบาท",
      outcome: "ผลลัพธ์",
      location: "สถานที่",
      client: "ลูกค้า",
      year: "ปี",
      openGallery: "ดูในสามมิติ",
      inRoom: "งานนี้ในห้อง",
    },
    gallery: {
      kicker: "ห้อง",
      title: "ห้องทำงาน",
      hint: "ลากเพื่อมอง · คลิกงาน · ลูกศรเพื่อเลื่อน",
      hintMobile: "ลากเพื่อมอง · แตะงาน",
      open: "เปิดเคส",
      close: "ปิด",
      loading: "กำลังจัดห้อง",
      inRoom: "ในห้อง",
    },
    studio: {
      kicker: "สตูดิโอ",
      title: "ห้องหนึ่งในพิษณุโลก",
      lede: "SIRAWAT × BALL เป็นห้องทำงานสองคน เราทำแบรนด์ พื้นที่ และโมชัน — มักในโปรเจกต์เดียวกัน และสนทนาเดียวกันเสมอ",
      p1: "จุดตั้งต้นคือโต๊ะร่วมและข้อเถียงเรื่องตัวพิมพ์ ตอนนี้มันเป็นวิธี: ศิรวัฒน์เขียนระบบ บอลสร้างที่ที่ระบบนั้นอยู่ ลูกค้ามาเพราะอัตลักษณ์ และกลับไปพร้อมห้อง ภาพยนตร์ หรือโลกสามมิติที่เดินได้",
      p2: "เรารับงานจำนวนน้อยต่อปี — บริการ วัฒนธรรม และผลิตภัณฑ์อิสระ แกลเลอรี 3D ในไซต์นี้ไม่ใช่คำอุปมา แต่เป็นวิธีเสนองาน: ในฐานะวัตถุในพื้นที่ ไม่ใช่กริดที่ลืมว่ามันมีน้ำหนัก",
      materials: "วัสดุ",
      bench: "โต๊ะงาน",
      sirawat: "ศิรวัฒน์",
      ball: "บอล",
      sirawatRole: "ครีเอทีฟไดเรกเตอร์",
      ballRole: "นักออกแบบพื้นที่",
      sirawatBio:
        "ดูแลอัตลักษณ์ งานบรรณาธิการ และระบบภาษา เรียนกราฟิก ออกแบบเป็นลำดับ กระดาษ และประโยคที่ห้องควรพูดออกมา",
      ballBio:
        "ดูแลพื้นที่ วัตถุ และสามมิติแบบเรียลไทม์ เรียนภายในและรูปทรงดิจิทัล คิดเป็นแสง มวล และวิธีที่กล้องควรเข้าไป",
    },
    contact: {
      kicker: "ติดต่อ",
      title: "เขียนถึงเรา",
      lede: "เล่าห้อง แบรนด์ หรือภาพยนตร์ เราตอบจากพิษณุโลก โดยปกติภายในไม่กี่วัน",
      name: "ชื่อ",
      email: "อีเมล",
      type: "ประเภทงาน",
      message: "ข้อความ",
      send: "ส่งข้อความ",
      sending: "กำลังส่ง",
      sentTitle: "ได้รับแล้ว",
      sentBody: "ขอบคุณ เราจะเขียนกลับจากห้องทำงาน",
      another: "ส่งอีกฉบับ",
      types: {
        brand: "อัตลักษณ์แบรนด์",
        space: "พื้นที่ / ภายใน",
        motion: "โมชัน / ภาพยนตร์",
        three: "สามมิติ / เว็บ",
        other: "อื่น ๆ",
      },
      addressLabel: "สตูดิโอ",
      address: "พิษณุโลก ประเทศไทย",
      mailLabel: "อีเมล",
      mail: "hello@sirawatball.studio",
      note: "ข้อความถูกเก็บบนอุปกรณ์นี้ เพื่อให้คุณออกแล้วกลับมาได้ ไม่ได้ส่งขึ้นเซิร์ฟเวอร์",
      errName: "กรุณาใส่ชื่อ",
      errEmail: "กรุณาใส่อีเมลที่ถูกต้อง",
      errMessage: "กรุณาเขียนสรุปงานสั้น ๆ",
    },
    footer: {
      wordmark: "SIRAWAT × BALL",
      line: "สตูดิโอสร้างสรรค์ · พิษณุโลก",
      work: "งาน",
      gallery: "แกลเลอรี 3D",
      drive: "ขับ",
      studio: "สตูดิโอ",
      contact: "ติดต่อ",
    },
    notFound: {
      title: "ห้องนี้ว่าง",
      body: "โปรเจกต์นั้นไม่อยู่ในสารบัญ",
      back: "กลับไปที่งาน",
    },
    fallback: {
      webgl: "เปิดห้องสามมิติบนอุปกรณ์นี้ไม่ได้ งานยังอยู่ในสารบัญ",
    },
    drive: {
      loading: "กำลังจัดลาน",
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function useCopy(): Copy {
  const lang = useLang((s) => s.lang);
  return copy[lang];
}

export function useLocale(): Lang {
  return useLang((s) => s.lang);
}
