import { opsZh } from "./ops/copy-zh";

/** Simplified Chinese public copy; proper names retain their original spelling. */
export const copyZh = {
  nav: {
    work: "作品",
    gallery: "3D 展厅",
    drive: "驾车探索",
    foodtruck: "餐车",
    studio: "工作室",
    contact: "联系",
    open: "打开菜单",
    close: "关闭菜单",
  },
  hero: {
    eyebrow: "彭世洛 · 创作空间",
    title: "SIRAWAT × BALL",
    lede: "来自泰国彭世洛的联合创作档案，汇集人工智能、网站、音乐与创意合作。",
    hint: "拖动环视 · 点击画框",
    hintMobile: "滑动环视 · 轻触画框",
    enterGallery: "进入 3D 展厅",
    enterDrive: "驾车探索园区",
    viewWork: "查看作品",
  },
  manifesto: {
    index: "01",
    kicker: "创作方向",
    title: "两种实践，一个共同的创作空间。",
    body: "Sirawat 从事人工智能、网站和太阳能项目。Ball Anekprasong 带来民谣现场与开放麦活动。这份作品集探索他们如何通过音乐、媒体与网络展开合作。",
  },
  selected: { index: "02", kicker: "精选", title: "走入空间，感受作品。", all: "全部项目" },
  duo: {
    index: "03",
    kicker: "创作者",
    title: "Sirawat × Ball",
    sirawatRole: "人工智能与网站项目",
    sirawatBody:
      "Sirawat（Ton）从事人工智能工作流、网站及 SIRINX 太阳能项目，通过交互展示将这些领域汇集在一起。",
    ballRole: "现场音乐与开放麦",
    ballBody: "Ball Anekprasong 举办民谣演出和开放麦活动，为大家提供歌唱与分享音乐的空间。",
    studioLink: "了解工作室",
  },
  process: {
    index: "04",
    kicker: "工作方法",
    title: "聆听、构思、制作、落地。",
    steps: [
      { n: "01", title: "聆听", body: "理解场地、文化、材料，以及尚未写下的需求。" },
      { n: "02", title: "构思", body: "确立语言识别与空间概念，同时明确让方案可行的约束。" },
      { n: "03", title: "制作", body: "构建系统、模型、动态影像与原型，从平面延伸到立体。" },
      { n: "04", title: "落地", body: "安装、上线、交接。离开现场后，作品仍应持续发挥作用。" },
    ],
  },
  cta: {
    kicker: "项目合作",
    title: "开始一个项目。",
    body: "与来自彭世洛的创作者探讨网站、创意媒体、现场音乐及合作机会。",
    button: "联系创作空间",
  },
  work: {
    kicker: "作品目录",
    title: "全部作品",
    lede: "这里汇集作品集中的概念研究。请先查看各项目的证据与状态，再判断是否属于已交付的客户项目。",
    filterAll: "全部",
    empty: "此类别暂无项目。",
    view: "查看项目",
    open3d: "以 3D 查看",
  },
  filters: { brand: "品牌", space: "空间", motion: "动态影像", culture: "文化" },
  case: {
    next: "下一个",
    prev: "上一个",
    back: "全部作品",
    role: "角色",
    outcome: "成果",
    location: "地点",
    client: "客户",
    year: "年份",
    openGallery: "在 3D 展厅中查看",
    inRoom: "作品在展厅中的位置",
  },
  gallery: {
    kicker: "展厅",
    title: "创作空间",
    hint: "拖动环视 · 点击作品 · 方向键切换",
    hintMobile: "拖动环视 · 轻触作品",
    open: "查看项目介绍",
    close: "关闭",
    loading: "正在准备展厅",
    inRoom: "展厅内",
  },
  studio: {
    kicker: "工作室",
    title: "彭世洛的一间创作室。",
    lede: "SIRAWAT × BALL 是 Sirawat（Ton）与 Ball Anekprasong 的联合创作档案，将技术与音乐汇集到同一个空间。",
    p1: "Sirawat 从事人工智能工作流、网站及 SIRINX 太阳能项目；Ball 带来民谣与开放麦活动。个人页面分别呈现各自的工作。",
    p2: "联合作品集是为音乐、媒体和网站合作提出的展示空间。3D 展厅呈现作品与概念；是否可称为已交付项目，取决于项目状态及相关证据。",
    materials: "材料",
    bench: "工作台",
    sirawat: "Sirawat",
    ball: "Ball",
    sirawatRole: "人工智能与网站项目",
    ballRole: "民谣音乐人与开放麦主持人",
    sirawatBio:
      "Sirawat（Ton）通过 SIRINX 从事人工智能、网站和太阳能项目。这份作品集将技术工作与创意展示连接起来。",
    ballBio: "Ball Anekprasong 演奏民谣并举办开放麦活动。他的页面聚焦音乐、表演和观众参与。",
  },
  contact: {
    kicker: "联系",
    title: "准备您的项目简报。",
    lede: "描述项目并在此设备保存副本，再通过您选择的渠道分享给工作室。",
    name: "姓名",
    email: "电子邮箱",
    type: "项目类型",
    message: "项目描述",
    send: "将简报保存在此设备",
    sending: "正在保存",
    sentTitle: "已保存在此设备。",
    sentBody:
      "简报尚未发送。请在下方下载或复制，然后自行分享给我们。当前浏览器的工作台会保留本地副本。",
    another: "准备另一份简报",
    types: {
      brand: "品牌识别",
      space: "空间与室内",
      motion: "动态影像与影片",
      three: "3D 与网站",
      other: "其他",
    },
    addressLabel: "工作室",
    address: "泰国彭世洛",
    note: "咨询内容保存在此设备，方便您离开后继续编辑，不会发送到服务器。",
    errName: "请输入姓名（2–120 个字符）。",
    errEmail: "请输入有效的电子邮箱。",
    errMessage: "请输入项目简述（8–10,000 个字符）。",
    channel: "回复渠道",
    handle: "LINE ID / 电子邮箱 / 电话",
    channels: { line: "LINE", email: "电子邮箱", phone: "电话" },
    errHandle: "请输入所选渠道的有效联系信息。",
    download: "下载简报",
    copyBrief: "复制简报",
    copied: "简报已复制，请通过您选择的渠道分享。",
    copyError: "无法复制，请下载简报。",
    handoff: "打开 Sirawat 的 Facebook",
    handoffNote: "此链接会打开所有者已确认的个人主页。请自行发送简报；打开链接不会自动发送内容。",
    deskHint: "打开本地工作台",
  },
  footer: {
    wordmark: "SIRAWAT × BALL",
    line: "创作空间 · 彭世洛",
    work: "作品",
    gallery: "3D 展厅",
    drive: "驾车探索",
    foodtruck: "餐车",
    studio: "工作室",
    contact: "联系",
  },
  notFound: { title: "这个房间暂时空着。", body: "作品目录中没有此项目。", back: "返回作品目录" },
  fallback: { webgl: "此设备无法打开 3D 展厅，您仍可在作品目录中浏览项目。" },
  drive: { loading: "正在准备园区" },
  ops: opsZh,
} as const;
