/** Simplified Chinese UI copy; application records and draft content stay separate. */
export const opsZh = {
  kicker: "本地运营",
  localTitle: "本地工作区",
  localNotice:
    "数据仅保存在此浏览器配置文件中，不会分享给工作室或其他设备。使用此配置文件的人可以查看数据。提醒仅在页面打开时更新；系统不会发送消息。",
  loading: "正在加载本地数据…",
  storageError:
    "无法读取或保存浏览器数据。本次更改尚未保存。请允许浏览器存储，或手动下载需求说明；原有数据未被覆盖。",
  retry: "重试本地存储",
  exportData: "下载本地备份",
  importData: "恢复备份",
  importError: "备份格式无效或超过 5 MB。原有数据未被覆盖。",
  restoreNonempty:
    "请在空工作区中恢复备份。可使用另一个浏览器配置文件查看此备份，以免覆盖已有工作。",
  imported: "备份已恢复到此设备。",
  backupNotice:
    "备份包含姓名、联系方式、消息和草稿，请妥善保管。恢复功能仅适用于空工作区，不会覆盖已有工作。",
  actionError: "无法保存本次操作。请重新加载本地数据后再试。",
  downloadDraft: "下载此草稿",
  desk: "工作台",
  marketing: "营销",
  automations: "自动任务",
  kit: "复用套件",
  deskTitle: "工作台",
  deskLede:
    "保存的需求说明会生成本地任务和提醒。可分配负责人、标记报价已准备以及关闭记录。这些操作不会联系工作室，也不会生成报价文件。",
  emptyDesk: "此视图暂无需求记录。联系表单保存的内容会显示在这里。",
  assign: "分配负责人",
  quote: "标记报价已准备",
  close: "关闭记录",
  assignee: "负责人",
  filters: {
    open: "未关闭",
    received: "已存至本地",
    assigned: "已分配",
    quoted: "报价已准备",
    closed: "已关闭",
  },
  status: { received: "已存至本地", assigned: "已分配", quoted: "报价已准备", closed: "已关闭" },
  jobs: { staff_task: "跟进任务", sla_watch: "时限提醒", quote_followup: "报价跟进" },
  jobStatus: {
    queued: "待处理",
    running: "处理中",
    done: "已完成",
    overdue: "已逾期",
    dead_letter: "已暂存",
  },
  marketingTitle: "渠道草稿",
  marketingLede:
    "在这里准备 LINE、Facebook、Instagram、TikTok、Google 和网站文案。“已就绪”仅表示三个语言版本的标题和正文达到完整性要求，并不表示已发送或经过事实核实。此页面没有自动发布功能。",
  editDraft: "编辑草稿正文",
  editDraftTitle: "编辑草稿标题",
  needsTranslation: "此旧版草稿尚无中文翻译。请补充中文标题和正文，再将三个语言版本标记为已就绪。",
  markReady: "标记为已就绪",
  noSend: "未启用发送",
  blockedBody:
    "请填写英语、泰语和中文标题，并确保每种语言的正文至少包含 20 个字符，再标记为已就绪。",
  draftStatus: { draft: "草稿", ready: "已就绪", blocked: "待补充" },
  channels: {
    line: "LINE 官方账号",
    facebook: "Facebook",
    instagram: "Instagram",
    tiktok: "TikTok",
    google: "Google 商家资料",
    web: "网站",
  },
  autoTitle: "自动任务",
  autoLede:
    "打开本页时检查本地提醒，页面保持打开时每 15 秒检查一次。重新访问时仍可查看逾期事项。没有后台执行程序，也不会向外部发送消息。",
  runTick: "检查任务时限",
  emptyJobs: "暂无任务。保存一份需求说明即可创建两项本地任务。",
  due: "到期时间",
  park: "暂存待处理",
  statOpen: "未关闭",
  statQueue: "处理中",
  statOverdue: "已逾期",
  statReady: "已就绪草稿",
  kitTitle: "复用套件",
  kitLede:
    "复用同一套核心功能：三维展厅、驾驶场景、需求表单、工作台、草稿和任务。为新项目替换图片、文案和渠道信息；请勿复制其他品牌的房型或未经确认的实时价格。",
  reuse: [
    {
      title: "访客网站",
      body: "首页、展厅、驾驶场景、作品与联系页面。先收集需求，不提供虚构日历或在线旅行平台预订。",
    },
    {
      title: "运营工作区",
      body: "本地工作台、营销草稿和时限提醒。获准接入实际连接器之前，数据保留在设备上。",
    },
    {
      title: "三维模型",
      body: "Blender MCP 分两步处理：先根据平面图搭建结构，再完善细节。GLB 模型尚未就绪时，使用基础几何场景。",
    },
  ],
  channelsTitle: "渠道分工",
  channelsLede: "这是建议的渠道方案，请根据受众调整。目前工作区尚未启用这些连接器。",
  channelFacts: [
    { channel: "LINE 官方账号", body: "规划一对一沟通和首次回复草稿。尚未启用群发。" },
    { channel: "Google", body: "通过地图和商家资料展示工作室。仅填写事实，不虚构评分。" },
    {
      channel: "Instagram / TikTok",
      body: "用于内容发现。三维展厅和驾驶场景可作为素材，关注实际咨询而非点赞数量。",
    },
    { channel: "Facebook", body: "用于社区交流和较长的创作记录，此工作区不提供直播销售。" },
  ],
  liveTitle: "此处可用",
  liveItems: [
    "三维展厅与驾驶场景",
    "本地需求记录、跟进任务和时限提醒",
    "工作台分配、报价状态和关闭记录",
    "带完整性检查的营销草稿",
    "泰语、简体中文与英语界面",
  ],
  blockedTitle: "此环境尚未提供",
  blockedItems: [
    "向 LINE、Meta 或 Google 发送内容",
    "Moshi-hook 设备配对（需在 Mac / Homebrew 环境完成）",
    "Blender 图形界面与 Astra 配额路由",
    "支付、酒店管理系统和已确认预订",
  ],
  studioOps: "运营工作区",
  deskCard: "工作台 — 需求与报价状态",
  marketingCard: "营销 — 六个渠道的草稿",
  autoCard: "自动任务 — 本地时限提醒",
  kitCard: "复用套件 — 核心功能的使用方法",
} as const;
