export const forgeCopy = {
  en: {
    kicker: "Studio tools / 01",
    title: "Shape your space",
    lede: "Choose a direction, adjust the atmosphere, and export your configuration to reuse.",
    configuration: "Configuration",
    format: "Configuration format · JSON v1",
    preset: "Business preset",
    presets: {
      "creative-studio": "Creative studio",
      "professional-service": "Professional service",
      "music-event": "Music & event",
    },
    titles: {
      "creative-studio": "A space for creative work.",
      "professional-service": "Turn an idea into a clear brief.",
      "music-event": "Make room for the next performance.",
    },
    theme: "Theme",
    themes: { ink: "Ink", slate: "Slate" },
    scene: "Scene",
    salon: "3D salon",
    static: "Static gallery",
    count: "Work count",
    resume: "Resume motion",
    pause: "Pause motion",
    sections: "Sections",
    sectionLabels: { profile: "Introduction", work: "Work", contact: "Contact" },
    export: "Export configuration",
    exported: "Configuration exported",
    invalid: "Invalid configuration",
    preview: "Website preview",
    previewLabel: "Live preview · concept imagery",
    evidence: "A configurable starting point. These studies are not verified client work.",
    studies: "Concept studies",
    brief: "Prepare a project brief",
    metrics: ["Brief completion", "Time to first selection", "Accessible experience"],
    unavailable: "N/A",
    analytics: "Analytics are not connected. Brief delivery is manual.",
  },
  th: {
    kicker: "เครื่องมือสตูดิโอ / 01",
    title: "ออกแบบพื้นที่ของคุณ",
    lede: "เลือกแนวทาง ปรับบรรยากาศ และดาวน์โหลดการตั้งค่าเพื่อนำไปใช้ต่อ",
    configuration: "การตั้งค่า",
    format: "รูปแบบการตั้งค่า · JSON v1",
    preset: "รูปแบบงาน",
    presets: {
      "creative-studio": "สตูดิโอสร้างสรรค์",
      "professional-service": "บริการวิชาชีพ",
      "music-event": "ดนตรีและอีเวนต์",
    },
    titles: {
      "creative-studio": "พื้นที่สำหรับงานสร้างสรรค์",
      "professional-service": "เปลี่ยนไอเดียเป็นบรีฟที่ชัดเจน",
      "music-event": "เปิดพื้นที่ให้การแสดงครั้งต่อไป",
    },
    theme: "บรรยากาศ",
    themes: { ink: "หมึกดำ", slate: "หินชนวน" },
    scene: "มุมมอง",
    salon: "ห้องแสดง 3D",
    static: "แกลเลอรีภาพ",
    count: "จำนวนผลงาน",
    resume: "เริ่มการเคลื่อนไหว",
    pause: "หยุดการเคลื่อนไหว",
    sections: "ส่วนประกอบ",
    sectionLabels: { profile: "แนะนำ", work: "ผลงาน", contact: "ติดต่อ" },
    export: "ดาวน์โหลดการตั้งค่า",
    exported: "ส่งออกการตั้งค่าแล้ว",
    invalid: "การตั้งค่าไม่ถูกต้อง",
    preview: "ตัวอย่างเว็บไซต์",
    previewLabel: "ตัวอย่างที่ปรับได้ · ภาพแนวคิด",
    evidence: "ตัวอย่างโครงสร้างสำหรับปรับใช้ ยังไม่ใช่ผลงานลูกค้าที่ได้รับการยืนยัน",
    studies: "ผลงานแนวคิด",
    brief: "เตรียมบรีฟงาน",
    metrics: ["การส่งบรีฟสำเร็จ", "เวลาสู่การเลือกผลงาน", "การเข้าถึงเนื้อหา"],
    unavailable: "ไม่มีข้อมูล",
    analytics: "ยังไม่ได้เชื่อมระบบวัดผล การส่งบรีฟใช้วิธีส่งเอง",
  },
  zh: {
    kicker: "工作室工具 / 01",
    title: "设计您的空间",
    lede: "选择创作方向、调整氛围，并导出配置以便重复使用。",
    configuration: "配置",
    format: "配置格式 · JSON v1",
    preset: "业务模板",
    presets: {
      "creative-studio": "创意工作室",
      "professional-service": "专业服务",
      "music-event": "音乐与活动",
    },
    titles: {
      "creative-studio": "为创作留出空间。",
      "professional-service": "将想法变成清晰的项目简报。",
      "music-event": "为下一场演出准备舞台。",
    },
    theme: "主题",
    themes: { ink: "墨黑", slate: "石板灰" },
    scene: "场景",
    salon: "3D 展厅",
    static: "静态画廊",
    count: "作品数量",
    resume: "恢复动画",
    pause: "暂停动画",
    sections: "页面组成",
    sectionLabels: { profile: "介绍", work: "作品", contact: "联系" },
    export: "导出配置",
    exported: "配置已导出",
    invalid: "配置无效",
    preview: "网站预览",
    previewLabel: "实时预览 · 概念图像",
    evidence: "这是可调整的起始方案。这些概念研究尚未被证实为客户交付作品。",
    studies: "概念研究",
    brief: "准备项目简报",
    metrics: ["简报完成率", "首次选择作品所需时间", "无障碍体验"],
    unavailable: "暂无数据",
    analytics: "尚未连接分析系统。项目简报需由您自行发送。",
  },
} as const;
