const en = {
  eyebrow: "S×B / MOBILE KITCHEN",
  title: "From the grounds.\nTo your next stop.",
  intro:
    "Drive the original 3D food truck, then prepare a real menu and a service route using your own details.",
  concept: "Original vehicle concept",
  drive: "Drive the food truck",
  plan: "Prepare your route",
  local: "Your workspace on this device",
  truth:
    "Details you enter are saved in this browser. They are not published or synced to a team. Map and contact links open external services when you choose them.",
  profile: "The truck",
  name: "Truck name",
  contact: "Contact or ordering URL (HTTPS)",
  currency: "Menu currency",
  save: "Save truck details",
  saved: "Saved on this device.",
  menu: "On the menu",
  menuEmpty: "Add your first dish with a name in all three languages.",
  addMenu: "Add dish",
  price: "Price",
  soldOut: "Sold out",
  available: "Listed on this device",
  remove: "Remove",
  edit: "Edit",
  cancel: "Cancel edit",
  updateMenu: "Update dish",
  route: "Next destinations",
  stopEmpty: "No service stops yet. Add a location and a planned time before opening directions.",
  addStop: "Add service stop",
  updateStop: "Update service stop",
  latitude: "Latitude",
  longitude: "Longitude",
  start: "Start · Bangkok (UTC+07)",
  end: "End · Bangkok (UTC+07)",
  labelEn: "Name · English",
  labelTh: "Name · ไทย",
  labelZh: "Name · 中文",
  directions: "Open directions",
  contactLink: "Open contact / ordering page",
  past: "Past plan",
  scheduled: "Planned stop",
  plannedNow: "Within planned hours · not live verified",
  ownerData: "Owner-entered details · confirm before visiting",
  zone: "All times shown in Bangkok time (UTC+07).",
  backup: "Take your plan with you",
  export: "Download food truck plan",
  import: "Import a plan (JSON, up to 128 KiB)",
  importPreview:
    "Review this plan before replacing the current one. Download your current plan first if you want to keep it.",
  apply: "Replace with this plan",
  dismiss: "Cancel import",
  noName: "Unnamed truck",
  items: "dishes",
  stops: "stops",
  invalid:
    "Check all three names, coordinates, HTTPS URL, price (up to 2 decimals), and time range. Nothing was saved.",
  large: "This file exceeds 128 KiB. Nothing was changed.",
  load: "The saved plan cannot be read. Download the original data below before restoring a valid backup.",
  saveError:
    "Your browser could not save the plan. Check storage availability and reload before retrying.",
  conflict: "The plan changed in another tab. Reload to use the latest version before saving.",
  raw: "Download original stored data",
  reload: "Reload latest plan",
  loading: "Reading your plan…",
  exportError: "The download could not start. Please try again.",
  body: "A moving studio for food, music and conversation.",
  detail:
    "An original Blender body, articulated wheels, and a procedural fallback keep the journey usable across devices. The drive scene is a virtual portfolio; service stops below use details you supply.",
  detail1: "01 / CREATE",
  detail2: "02 / PLAN",
  detail3: "03 / CONNECT",
  text1: "Explore the truck in the 3D grounds.",
  text2: "Build a menu and dated service stops.",
  text3: "Open directions or your own contact page.",
};
type Copy = { [K in keyof typeof en]: string };
const th: Copy = {
  eyebrow: "S×B / ครัวเคลื่อนที่",
  title: "จากโลกสามมิติ\nสู่จุดหมายถัดไป",
  intro: "ขับฟู้ดทรักสามมิติที่ออกแบบขึ้นใหม่ แล้วเตรียมเมนูและแผนจุดจอดด้วยข้อมูลจริงของคุณ",
  concept: "โมเดลรถแนวคิดที่ออกแบบขึ้นใหม่",
  drive: "ขับฟู้ดทรัก",
  plan: "เตรียมเส้นทาง",
  local: "พื้นที่ทำงานบนอุปกรณ์นี้",
  truth:
    "ข้อมูลที่กรอกจะเก็บในเบราว์เซอร์นี้ ยังไม่เผยแพร่หรือซิงก์กับทีม ลิงก์แผนที่และช่องทางติดต่อจะเปิดบริการภายนอกเมื่อคุณเลือกใช้งาน",
  profile: "รถของคุณ",
  name: "ชื่อรถ",
  contact: "ลิงก์ติดต่อหรือสั่งอาหาร (HTTPS)",
  currency: "สกุลเงินในเมนู",
  save: "บันทึกข้อมูลรถ",
  saved: "บันทึกบนอุปกรณ์นี้แล้ว",
  menu: "เมนูบนรถ",
  menuEmpty: "เพิ่มเมนูแรกพร้อมชื่อทั้งสามภาษา",
  addMenu: "เพิ่มเมนู",
  price: "ราคา",
  soldOut: "หมดแล้ว",
  available: "รายการบนอุปกรณ์นี้",
  remove: "ลบ",
  edit: "แก้ไข",
  cancel: "ยกเลิกการแก้ไข",
  updateMenu: "บันทึกเมนู",
  route: "จุดหมายถัดไป",
  stopEmpty: "ยังไม่มีจุดจอด เพิ่มสถานที่และเวลาตามแผนก่อนเปิดเส้นทาง",
  addStop: "เพิ่มจุดจอด",
  updateStop: "บันทึกจุดจอด",
  latitude: "ละติจูด",
  longitude: "ลองจิจูด",
  start: "เริ่ม · กรุงเทพฯ (UTC+07)",
  end: "สิ้นสุด · กรุงเทพฯ (UTC+07)",
  labelEn: "ชื่อ · English",
  labelTh: "ชื่อ · ไทย",
  labelZh: "ชื่อ · 中文",
  directions: "เปิดเส้นทาง",
  contactLink: "เปิดหน้าติดต่อ / สั่งอาหาร",
  past: "แผนที่ผ่านมา",
  scheduled: "จุดจอดตามแผน",
  plannedNow: "อยู่ในเวลาตามแผน · ยังไม่ยืนยันหน้างาน",
  ownerData: "ข้อมูลที่เจ้าของกรอก · ยืนยันก่อนเดินทาง",
  zone: "ทุกเวลาแสดงตามเวลากรุงเทพฯ (UTC+07)",
  backup: "นำแผนไปใช้ต่อ",
  export: "ดาวน์โหลดแผนฟู้ดทรัก",
  import: "นำเข้าแผน (JSON ไม่เกิน 128 KiB)",
  importPreview: "ตรวจแผนนี้ก่อนแทนที่แผนปัจจุบัน ดาวน์โหลดแผนเดิมก่อนหากต้องการเก็บไว้",
  apply: "แทนที่ด้วยแผนนี้",
  dismiss: "ยกเลิกนำเข้า",
  noName: "รถที่ยังไม่ได้ตั้งชื่อ",
  items: "เมนู",
  stops: "จุดจอด",
  invalid:
    "ตรวจชื่อทั้งสามภาษา พิกัด ลิงก์ HTTPS ราคา (ทศนิยมไม่เกิน 2 ตำแหน่ง) และช่วงเวลา ยังไม่มีการบันทึก",
  large: "ไฟล์เกิน 128 KiB ข้อมูลเดิมยังไม่เปลี่ยน",
  load: "อ่านแผนที่บันทึกไว้ไม่ได้ ดาวน์โหลดข้อมูลต้นฉบับด้านล่างก่อนกู้คืนจากไฟล์ที่ถูกต้อง",
  saveError: "เบราว์เซอร์บันทึกแผนไม่ได้ ตรวจพื้นที่จัดเก็บแล้วโหลดหน้าใหม่ก่อนลองอีกครั้ง",
  conflict: "มีการเปลี่ยนแผนในแท็บอื่น โหลดหน้าใหม่เพื่อใช้ข้อมูลล่าสุดก่อนบันทึก",
  raw: "ดาวน์โหลดข้อมูลต้นฉบับ",
  reload: "โหลดแผนล่าสุด",
  loading: "กำลังอ่านแผน…",
  exportError: "เริ่มดาวน์โหลดไม่ได้ กรุณาลองอีกครั้ง",
  body: "สตูดิโอเคลื่อนที่สำหรับอาหาร ดนตรี และบทสนทนา",
  detail:
    "ตัวรถสร้างด้วย Blender พร้อมล้อที่เคลื่อนไหวและโมเดลสำรองเพื่อรองรับอุปกรณ์ที่หลากหลาย ฉากขับรถเป็นพอร์ตโฟลิโอเสมือน ส่วนจุดจอดด้านล่างใช้ข้อมูลที่คุณกรอก",
  detail1: "01 / สร้าง",
  detail2: "02 / วางแผน",
  detail3: "03 / เชื่อมต่อ",
  text1: "สำรวจรถในฉากขับสามมิติ",
  text2: "จัดเมนูและกำหนดวันเวลาจุดจอด",
  text3: "เปิดเส้นทางหรือหน้าติดต่อของคุณ",
};
const zh: Copy = {
  eyebrow: "S×B / 移动厨房",
  title: "从虚拟天地\n驶向下一站",
  intro: "驾驶原创三维餐车，再用自己的实际资料规划菜单和服务地点。",
  concept: "原创餐车概念模型",
  drive: "驾驶餐车",
  plan: "规划路线",
  local: "此设备上的工作区",
  truth:
    "输入的资料保存在当前浏览器中，尚未发布，也不会同步给团队。只有点击后，地图和联系链接才会打开外部服务。",
  profile: "你的餐车",
  name: "餐车名称",
  contact: "联系或点餐网址（HTTPS）",
  currency: "菜单币种",
  save: "保存餐车资料",
  saved: "已保存在此设备上。",
  menu: "车上菜单",
  menuEmpty: "添加第一道菜，并填写三种语言的名称。",
  addMenu: "添加菜品",
  price: "价格",
  soldOut: "已售罄",
  available: "此设备上的菜单项目",
  remove: "删除",
  edit: "编辑",
  cancel: "取消编辑",
  updateMenu: "更新菜品",
  route: "下一站",
  stopEmpty: "暂无服务地点。添加地点和计划时间后，即可打开路线。",
  addStop: "添加服务地点",
  updateStop: "更新服务地点",
  latitude: "纬度",
  longitude: "经度",
  start: "开始 · 曼谷时间（UTC+07）",
  end: "结束 · 曼谷时间（UTC+07）",
  labelEn: "名称 · English",
  labelTh: "名称 · ไทย",
  labelZh: "名称 · 中文",
  directions: "打开路线",
  contactLink: "打开联系 / 点餐页面",
  past: "过去的计划",
  scheduled: "计划停靠点",
  plannedNow: "处于计划时段 · 未实时核实",
  ownerData: "车主输入的资料 · 前往前请确认",
  zone: "所有时间均为曼谷时间（UTC+07）。",
  backup: "随身携带你的计划",
  export: "下载餐车计划",
  import: "导入计划（JSON，最大 128 KiB）",
  importPreview: "替换当前计划前请先检查。如需保留原计划，请先下载备份。",
  apply: "用此计划替换",
  dismiss: "取消导入",
  noName: "未命名餐车",
  items: "道菜品",
  stops: "个停靠点",
  invalid: "请检查三种语言的名称、坐标、HTTPS 网址、价格（最多两位小数）及时间范围。尚未保存。",
  large: "文件超过 128 KiB，原资料未更改。",
  load: "无法读取已保存的计划。请先下载下方的原始资料，再用有效备份恢复。",
  saveError: "浏览器无法保存计划。请检查存储空间并刷新页面后重试。",
  conflict: "另一个标签页已更改计划。保存前请刷新以读取最新版本。",
  raw: "下载原始存储资料",
  reload: "重新加载最新计划",
  loading: "正在读取计划…",
  exportError: "无法开始下载，请重试。",
  body: "让美食、音乐与交谈一起出发。",
  detail:
    "原创 Blender 车身、可转动的车轮和程序化备用模型，让不同设备都能继续旅程。驾驶场景是虚拟作品集；下方服务地点使用你提供的资料。",
  detail1: "01 / 创作",
  detail2: "02 / 规划",
  detail3: "03 / 连接",
  text1: "在三维场景中探索餐车。",
  text2: "创建菜单并安排停靠时间。",
  text3: "打开路线或自己的联系页面。",
};
export const foodtruckCopy = { en, th, zh };
